### PR TITLE
Add ApplicationLogger (needed by libgdx 1.9.6)

### PR DESCRIPTION
**Pull request by yuripourre**

### CODE REVIEW

**Comment by yangweigbh** [comment]
if add the applicationlogger, maybe we should use it in debug, log and error

**Comment by yuripourre** [comment]
I added this code copying from [AndroidApplication](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java#L80)

Without this modifications the code doesn't compile with Libgdx 1.9.6

**Comment by yuripourre** [comment]
It can be used for debug, log and error, for sure.

**Comment by yuripourre** [comment]
@yangweigbh
Can you please accept this PR?

**Comment by yangweigbh** [comment]
already update to 1.9.7, thanks

**Pull request closed without merging**
